image: docker:latest
services:
  - name: docker:dind
    alias: docker

variables:
  AZURE_TENANT_ID: $AZURE_TENANT_ID
  AZURE_CLIENT_ID: $AZURE_CLIENT_ID
  AZURE_CLIENT_SECRET: $AZURE_CLIENT_SECRET
  AZURE_APP_NAME: "cs655"
  AZURE_RG_NAME: "docker-apps"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  DCOKER_REGISTRY: "hesamian.azurecr.io"
  DOCKER_TAG: "hesamian.azurecr.io/cs655"

stages:
  - deploy

docker-build:
  stage: deploy
  resource_group: azure
  only:
    - master
  allow_failure: false
  before_script:
    - apk update
    - apk --no-cache add make bash curl py-pip
    - apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python- dev
    - pip install azure-cli
    - apk del --purge build
  script:
    - docker build . -t temp
    - docker tag temp $DOCKER_TAG
    - az login --service-principal    \
        -t $AZURE_TENANT_ID           \
        -u $AZURE_CLIENT_ID           \
        -p $AZURE_CLIENT_SECRET
    - az acr login --name $DCOKER_REGISTRY
    - docker push $DOCKER_TAG
    - az webapp config container set  \
      --resource-group $AZURE_RG_NAME \
      --name $AZURE_APP_NAME          \
      --docker-custom-image-name $DOCKER_TAG
    - az webapp restart               \
      --resource-group $AZURE_RG_NAME \
      --name $AZURE_APP_NAME