image: docker:stable
services:
  - name: docker:dind
    alias: docker

variables:
  AZURE_TENANT_ID: $AZURE_TENANT_ID
  AZURE_CLIENT_ID: $AZURE_CLIENT_ID
  AZURE_CLIENT_SECRET: $AZURE_CLIENT_SECRET
  AZURE_APP_NAME: "cs655"
  AZURE_RG_NAME: "docker-apps"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_REGISTRY: "hesamian"
  DOCKER_TAG: "$DOCKER_REGISTRY.azurecr.io/$AZURE_APP_NAME"
  DOCKER_TAG_SUFFIX: "latest"

stages:
  - deploy

docker-build:
  stage: deploy
  resource_group: azure
  only:
    - master
  allow_failure: false
  before_script:
    - apk --no-cache add curl py3-pip
        gcc musl-dev python3-dev libffi-dev
        openssl-dev cargo make
    - pip install --upgrade pip
    - pip install azure-cli
  script:
    - docker build . -t temp
    - docker tag temp $DOCKER_TAG:$DOCKER_TAG_SUFFIX
    - az login --service-principal
        -t $AZURE_TENANT_ID
        -u $AZURE_CLIENT_ID
        -p $AZURE_CLIENT_SECRET
    - az acr login --name $DOCKER_REGISTRY
    - docker push $DOCKER_TAG:$DOCKER_TAG_SUFFIX
    - az webapp config container set
        --resource-group $AZURE_RG_NAME
        --name $AZURE_APP_NAME
        --docker-custom-image-name $DOCKER_TAG:$DOCKER_TAG_SUFFIX
    - az webapp restart
        --resource-group $AZURE_RG_NAME
        --name $AZURE_APP_NAME